//
// Created by Danial javady on 2023-04-24.
//

#ifndef MACHINELALGOS_SRC_ALGORITHMS_MODULEALGORITHMS_H_
#define MACHINELALGOS_SRC_ALGORITHMS_MODULEALGORITHMS_H_


namespace ModuleAlgos {
	template <class T>
	T forward();
}
#endif //MACHINELALGOS_SRC_ALGORITHMS_MODULEALGORITHMS_H_
